; PlatformIO Project Configuration File
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_type = release
upload_speed = 512000
monitor_speed = 115200

; --- Use our self-contained partition scheme file from the project root ---
board_build.partitions = partitions.csv

; --- Upload Settings for OTA Development ---
#upload_protocol = espota
#upload_port = wrist-strap-monitor.local

; --- Library Dependencies ---
lib_deps =
	bblanchon/ArduinoJson
	adafruit/Adafruit INA219
	marvinroger/AsyncMqttClient
	me-no-dev/ESPAsyncWebServer
	https://github.com/me-no-dev/AsyncTCP.git