[project]
name = "wrist-strap-web-api"
version = "0.1.0"
description = "API for the Wrist Strap Monitor System"
authors = [
    { name = "Tan Nguyen", email = "tan.nguyenthanhduy@vn.sharp-world.com" },
]
dependencies = [
    "fastapi>=0.111.0",
    "uvicorn[standard]>=0.29.0",
    "pymongo>=4.8.0",
    "PyJWT[cryptography]>=2.8.0",
    "pydantic-settings>=2.2.1",
]
requires-python = ">=3.9"
readme = "README.md"
license = { text = "MIT" }

[tool.pdm]
distribution = false
